version: "3"
services:
  halo:
    image: halohub/halo:2.14
    container_name: halo2
    restart: on-failure:3
    depends_on:
      - halodb
    volumes:
      - /data/Halo/halo2:/root/.halo2
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8090/actuator/health/readiness || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    command:
      - --spring.r2dbc.url=r2dbc:pool:postgresql://halodb/halo
      - --spring.r2dbc.username=halo
      - --spring.r2dbc.password=your password
      - --spring.sql.init.platform=postgresql
      - --halo.external-url=http://120.78.156.217:8090/
      - --halo.security.initializer.superadminusername=admin
      - --halo.security.initializer.superadminpassword=mjMJ@2024
  halodb:
    image: postgres:15.4
    container_name: halodb2
    restart: on-failure:3
    volumes:
      - /data/Halo/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U halo -d halo"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=your password
      - POSTGRES_USER=halo
      - POSTGRES_DB=halo
      - PGUSER=halo

  frps:
    image: ryaning/frps
    container_name: frps2
    restart: always
    volumes:
      - /data/frp/frps.ini:/etc/frp/frps.ini
    ports:
      - "7000:7000"
      - "7001:7001"
      - "10080:10080"
      - "10443:10443"
      - "5000:5000"
      - "3000:3000"
      - "8222:8222"
      - "8223:8223"
      - "8224:8224"
      - "8225:8225"
      - "8226:8226"
      - "8227:8227"
      - "8228:8228"
      - "8229:8229"
      - "8230:8230"
      - "8231:8231"
      - "8232:8232"
      - "8233:8233"
      - "8234:8234"
      - "8235:8235"
      - "8236:8236"
      - "8237:8237"
      - "8238:8238"
      - "8239:8239"
      - "8240:8240"
      - "8241:8241"
      - "8242:8242"
      - "8243:8243"
      - "8244:8244"
      - "8096:8096"

  nginx:
    image: nginx
    container_name: nginx2
    ports:
      - "80:80"
    volumes:
      - /data/nginx/html:/usr/share/nginx/html:ro
      - /data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/conf/conf.d:/etc/nginx/conf.d
      - /data/nginx/log:/var/log/nginx
    restart: always