--- 
#Uninstall node_exporter

- name: UnInstall node_exporter
  hosts: centos7
  become: true
  vars:
      version: 1.8.2 
      tar_package: node_exporter-{{ version }}.linux-amd64.tar.gz
      download_url: http://mirrors.sunline.cn/prometheus/linux/{{ tar_package }}
      external_url: https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/{{  tar_package }}
      download_path: /usr/local/src
      install_path: /usr/local/node_exporter

  tasks:
    - name: Check if node_exporter is already installed
      stat:
        path: "{{ install_path }}"
      register: node_exporter_installed

    - name: Exit if node_exporter is not installed
      when: not node_exporter_installed.stat.exists
      debug:
        msg: "node_exporter is not installed. Exiting the playbook."
      failed_when: true
  
    - name: Stop node_exporter service
      systemd:
        name: node_exporter
        state: stopped
        daemon_reload: yes
        enabled: no
    
    - name: Remove node_exporter service
      file:
        path: /usr/lib/systemd/system/node_exporter.service
        state: absent
        mode: 0644
    
    - name: Remove node_exporter
      file:
        path: "{{ install_path }}"
        state: absent