version: '3.3'
services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql
    restart: always
    ports:
      - 3307:3306
    networks:
      - bridge
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: sunline
      MYSQL_DATABASE: oneapi
    volumes:
      - ./mysql:/var/lib/mysql
  oneapi:
    container_name: oneapi
    image: ghcr.io/songquanpeng/one-api:latest
    ports:
      - 3000:3000
    depends_on:
      - mysql
    networks:
      - bridge
    restart: always
    environment:
      - SQL_DSN=root:sunline@tcp(mysql:3306)/oneapi
      - SESSION_SECRET=oneapikey
      - MEMORY_CACHE_ENABLED=true
      - BATCH_UPDATE_ENABLED=true
      - BATCH_UPDATE_INTERVAL=10
      - INITIAL_ROOT_TOKEN=sunline
    volumes:
      - ./oneapi:/data
networks:
  bridge: