---
- name: Create and configure user
  hosts: all
  become: true
  vars:
    username: josh
    password: "{{ 'josh2024' | password_hash('sha512') }}"
    groups: wheel
    append: yes
    grant_nopass: true
  tasks:
    - name: Ensure the user is created
      user:
        name: "{{ username }}"
        password: "{{ password }}"
        groups: wheel
        append: yes

    - name: Allow passwordless sudo if selected
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^{{ username }} ALL=.*NOPASSWD: ALL"
        line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"
      when: grant_nopass

    - name: Test SSH login as the new user
      shell: whoami
      register: ssh_test
      delegate_to: "{{ inventory_hostname }}"
      remote_user: "{{ username }}"

    - name: Display SSH login test result
      debug:
        msg: "Login test result for {{ username }}: {{ ssh_test.stdout }}"

    - name: Modify user ID and group ID to root in /etc/passwd
      shell: |
        sed -i "s#^\({{ username }}:[^:]*:\)[0-9]\+:[0-9]\+\(.*\)#\10:0\2#" /etc/passwd
      when: username == username