- ansible.builtin.include_vars: variables.yml

- ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Unsupported OS Family
  fail:
    msg: "This role only supports RedHat and Debian families. Detected: {{ ansible_os_family }}"
  when: ansible_os_family not in ['RedHat', 'Debian']
