---
node_export_version: "1.8.2"
tar_package: node_exporter-{{ node_export_version }}.linux-amd64.tar.gz
install_path: /usr/local/node_exporter
download_path: /usr/local/src
internal_url: http://mirrors.sunline.cn/prometheus/linux/{{ tar_package }}
external_url: https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/{{  tar_package }}