- name: centos8 dnf test
  hosts: centos8
  become: true
  tasks:
    - name: 更新 DNF 缓存
      dnf: 
        name: "*"
        state: latest
    - name: 安装 EPEL 仓库
      dnf:
        name: epel-release
        state: present

    - name:  install nmap
      dnf:
        name: nmap
        state: present