
version: '3.3'
services:
  pg:
    image: ankane/pgvector:v0.5.0 # git
    container_name: pg
    restart: always
    ports: 
      - 5432:5432
    networks:
      - fastgpt
    environment:
      - POSTGRES_USER=sun
      - POSTGRES_PASSWORD=sunline2024
      - POSTGRES_DB=postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  mongo:
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/mongo:5.0.18
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - fastgpt
    command: mongod --keyFile /data/mongodb.key --replSet rs0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sun
      - MONGO_INITDB_ROOT_PASSWORD=sunline2024
    volumes:
      - ./mongo/data:/data/db
    entrypoint:
      - bash
      - -c
      - |
        openssl rand -base64 128 > /data/mongodb.key
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        echo 'const isInited = rs.status().ok === 1
        if(!isInited){
          rs.initiate({
              _id: "rs0",
              members: [
                  { _id: 0, host: "mongo:27017" }
              ]
          })
        }' > /data/initReplicaSet.js
        exec docker-entrypoint.sh "$$@" &

        until mongo -u sun -p sunline2024 --authenticationDatabase admin --eval "print('waited for connection')" > /dev/null 2>&1; do
          echo "Waiting for MongoDB to start..."
          sleep 2
        done

        mongo -u sun -p sunline2024 --authenticationDatabase admin /data/initReplicaSet.js

        wait $$!
  fastgpt:
    container_name: fastgpt
    image: registry.cn-hangzhou.aliyuncs.com/fastgpt/fastgpt:v4.7 # git
    ports:
      - 9897:3000
    networks:
      - fastgpt
    depends_on:
      - mongo
      - pg
    restart: always
    environment:
      - DEFAULT_ROOT_PSW=sunline2024
      - OPENAI_BASE_URL=http://172.18.0.104:3000/v1
      - CHAT_API_KEY=sk-Vz6HDEC74r73Y0F312E39d1072B443Fa935e766434FcD97e
      - DB_MAX_LINK=30
      - TOKEN_KEY=any
      - ROOT_KEY=root_key
      - FILE_TOKEN_KEY=filetoken
      - MONGODB_URI=mongodb://sun:sunline2024@mongo:27017/fastgpt?authSource=admin
      - PG_URL=postgresql://sun:sunline2024@pg:5432/postgres
    volumes:
      - ./config.json:/app/data/config.json
      - ./fastgpt/tmp:/app/tmp
networks:
  fastgpt:
    ipam:
      driver: default
      config:
        - subnet: 172.199.0.0/16