version: '3.1'

services:
# 多用户版
  read_all:
    image: hectorqin/reader
    container_name: reader   #容器名,可自行修改
    networks:
      - reader_network
    restart: always
    ports:
      - 4396:8080   #4396端口映射可自行修改
    volumes:
      - /data/reader/logs:/logs   #log映射目录 /root/data/docker_data/reader/logs 映射目录可自行修改
      - /data/reader/storage:/storage   #数据映射目录 /root/data/docker_data/reader/storage 映射目录可自行修改
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - READER_APP_SECURE=true   #开启登录鉴权，开启后将支持多用户模式
      - READER_APP_CACHECHAPTERCONTENT=true   #是否开启缓存章节内容 V2.0
      - READER_APP_SECUREKEY=dream13889   #管理员密码  可自行修改
# 自动更新docker
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    networks:
      - reader_network
    restart: always
    # 环境变量,设置为上海时区
    environment:
        - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: reader watchtower --cleanup --schedule "0 0 4 * * *"

networks:
  reader_network:
    name: reader_network
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
