site_dir: "site"
site_url: http://joshzhong.top/
site_name: JoshZhong
site_description: '记录 Bio+IT 相关知识，沉淀生活，记录点滴。'

# Docs 
docs_dir: "docs"

# Repository
repo_name: JoshZhong-MkDoc
repo_url: https://github.com/joshzhong66/JoshZhong-MkDoc
edit_uri: edit/main/docs/
site_author: Steven Shum

# Copyright
copyright: 版权所有

theme:
  name: material
  language: zh
  custom_dir: overrides
  favicon: assets/logo.ico
  logo: assets/octocat.png
  font:
    text: "Microsoft Yahei"
    code: "Consolas,Courier,courier new,stkaiti,kaiti,simkai,monospace"
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.sections
    - navigation.path         
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.footer
  palette:
    - scheme: default
      primary: grey
      accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    
markdown_extensions:
    - admonition
    - pymdownx.details
    - md_in_html
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - smarty
    - toc:
        permalink: True
        separator: "-"
        toc_depth: 5
        slugify: !!python/object/apply:pymdownx.slugs.slugify
            kwds:
                case: lower
    - pymdownx.highlight
    - pymdownx.arithmatex:
        generic: true

plugins:
  - rss:
      enabled: True
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      pretty_print: True
      length: 1000
      date_from_meta:
          as_creation: "date"
          as_update: "date"
      abstract_chars_count: -1
      match_path: "(blog/posts|flinks|galaxy|message|note|readme|tech|yuque)/.*"
  - glightbox:
      auto_caption: false    
      caption_position: bottom
  - search:
      lang:
          - en
          - zh
  - git-revision-date-localized:
      type: iso_date
      timezone: Asia/Shanghai
      fallback_to_build_date: true
      exclude:
          - blog/archive/*
          - blog/category/*
  - awesome-pages:
      order: desc
      sort_type: natural
      order_by: filename
  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"
      archive: true
      categories: true
      pagination: true
      pagination_per_page: 10
      post_url_date_format: ""
      pagination_if_single_page: true

hooks:
  - hooks.py
  - meta_slugs.py
      
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shenweiyan
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/weiyanshum
      name: Twitter      
    - icon: fontawesome/brands/mastodon
      link: https://genomic.social/@weiyanshum
      name: Mastodon
  analytics:
    provider: custom
    property: foobar

extra_css:
  - css/extra.css

extra_javascript:
    - js/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.bootcss.com/mathjax/3.0.5/es5/tex-mml-chtml.js      
